[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tiktok-mcp"
version = "0.1.0"
description = "A Mcp server for tiktok"
dependencies = [
    "fastmcp==2.11.0",
    "requests>=2.32.5",
]
